version: "3.9"
services:
  api_meun_planner:
    image: michalkolarzyk/api_menu_planner
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:443;http://+:80
      - MENU_PLANNER_CONNECTION_STRING=mongodb://host.docker.internal:27017
    ports:
      - 8000:80
      - 8001:81