export const SET_USER = "SET_USER";

export const SET_DISH = "SET_DISH";

export const SET_RECIPE = "SET_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE"
export const ADD_RECIPE_STEP = "ADD_RECIPE_STEP";
export const UPDATE_RECIPE_STEP = "UPDATE_RECIPE_STEP";
export const REMOVE_RECIPE_STEP = "REMOVE_RECIPE_STEP";
export const ADD_RECIPE_TAG = "ADD_RECIPE_TAG";
export const REMOVE_RECIPE_TAG = "REMOVE_RECIPE_TAG";
export const SET_RECIPE_MODE = "SET_RECIPE_MODE";
export const SET_RECIPE_IS_LOADING = "SET_RECIPE_IS_LOADING";
export const SET_RECIPE_DELETED_SUCCESFULLY = "SET_RECIPE_DELETED_SUCCESFULLY";

export const SET_NEWRECIPE = "SET_NEWRECIPE";
export const SET_NEWRECIPE_CREATED_SUCCESFULLY = "SET_NEWRECIPE_CREATED_SUCCESFULLY";
export const SET_NEWRECIPE_ERROR = "SET_NEWRECIPE_ERROR";

export const SET_RECIPES = "SET_RECIPES";
export const SET_RECIPES_IS_LOADING = "SET_RECIPES_IS_LOADING";
export const SET_RECIPES_SORTED_BY = "SET_RECIPES_SORTED_BY";
export const SET_RECIPES_SKIP = "SET_RECIPES_SKIP";
export const SET_RECIPES_TAKE = "SET_RECIPES_TAKE";
export const SET_RECIPES_SELECTED_TAGS = "SET_RECIPES_SELECTED_TAGS";
export const SET_RECIPES_TAGS = "SET_RECIPES_TAGS";

export const SET_REGISTRATION_USER = "SET_REGISTRATION_USER";
export const SET_REGISTRATION_ERROR = "SET_REGISTRATION_ERROR";
export const SET_REGISTRATION_USER_SUCCESFULLY_CREATED = "SET_REGISTRATION_USER_SUCCESFULLY_CREATED";

