export const SET_USER = "SET_USER";

export const SET_DISH = "SET_DISH";

export const SET_RECIPE = "SET_RECIPE";
export const DELETE_RECIPE = "DELETE_RECIPE"
export const ADD_RECIPE_STEP = "ADD_RECIPE_STEP";
export const UPDATE_RECIPE_STEP = "UPDATE_RECIPE_STEP";
export const REMOVE_RECIPE_STEP = "REMOVE_RECIPE_STEP";
export const SET_RECIPE_EDIT_MODE = "SET_RECIPE_EDIT_MODE";
export const SET_RECIPE_IS_LOADING = "SET_RECIPE_IS_LOADING";

export const SET_NEWRECIPE = "SET_NEWRECIPE";

export const SET_RECIPES = "SET_RECIPES";
export const SET_RECIPES_IS_LOADING = "SET_RECIPES_IS_LOADING";
export const SET_RECIPES_SORTED_BY = "SET_RECIPES_SORTED_BY";
